author = Artur Tarassow
email = atecon@posteo.de
version = 0.3
date = 2022-11-11
min-version = 2020a
description = Compute VAR model estimates recursively
tags = C32 C52
public = setupVARrec VARrec VARrecplot
help = VARrec_help.txt
sample-script = VARrec_sample.inp
data-requirement = needs-time-series-data